# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Service\GoogleCloudStorageService:
        arguments:
            $serviceAccountJsonPath: '%env(resolve:GOOGLE_SERVICE_ACCOUNT_JSON_PATH)%'
            $bucketName: '%env(GCS_BUCKET_NAME)%'
            $logger: '@monolog.logger'

    App\Command\BackupStorageCommand:
        arguments:
            $logger: '@monolog.logger'
            $localStorageFolder: "%env(LOCAL_STORAGE_FOLDER)%"
            $gcsPrefixPath: "%env(GCS_STORAGE_PREFIX_PATH)%"

    App\Service\EmailService:
        arguments:
            $from: '%env(MAILER_FROM)%'
            $to: '%env(MAILER_TO)%'

    App\Service\DatabaseBackupService:
        arguments:
            $blogDatabaseUrl: '%env(BLOG_DATABASE_URL)%'

    App\Command\BackupMySQLCommand:
        arguments:
            $logger: '@monolog.logger'
            $gcsPrefixPath: "%env(GCS_MYSQL_PREFIX_PATH)%"

